# Generated by Django 5.2.5 on 2025-08-15 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produit', '0002_alter_product_price_alter_product_quantity'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('price__gte', 0)), name='price_positive'),
        ),
    ]
