# Generated by Django 5.2.5 on 2025-08-15 07:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produit', '0003_product_price_positive'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='product',
            name='price_positive',
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
